#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Mar 12 02:41:54 2022

@author: jackhirschman
"""

import numpy as np
import matplotlib.pyplot as plt

time_vector = np.linspace(-8.191e-11,8.192e-11,num=1400000)
input_eField = np.exp(-1.386*((time_vector-0)/(246*10**(-15)))**2)*np.exp(-1j*299792458/(1024e-9)*2*np.pi*time_vector)
plt.plot(time_vector,input_eField)
plt.plot(time_vector,np.abs(input_eField))
plt.xlim(-.05e-12,.05e-12)
plt.show()

freq_vector = np.fft.fftfreq(n=time_vector.shape[0], d = (time_vector[1]-time_vector[0]))
ft = np.fft.fft(input_eField)
plt.plot((freq_vector),np.abs(ft)**2)
ind = np.argmax(np.abs(ft)**2)
print(freq_vector[ind]*1e-14)